-- ============================================
-- FidanX v2 — Ek Tablolar Migration Script
-- Tarih: 2026-03-05
-- Hedef: SASERA2025 (192.168.1.100)
-- Bu tablolar uygulamanın eski modülleri için gereklidir.
-- ============================================

USE SASERA2025;
GO

-- Plants
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'Plants')
CREATE TABLE Plants (
    Id INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    TenantId NVARCHAR(50) NOT NULL,
    Name NVARCHAR(MAX) NOT NULL,
    Category NVARCHAR(100) NULL,
    Type NVARCHAR(50) NULL,
    CurrentStock FLOAT NULL DEFAULT (0),
    WholesalePrice FLOAT NULL DEFAULT (0),
    RetailPrice FLOAT NULL DEFAULT (0),
    ViyolCount INT NULL DEFAULT (0),
    CuttingCount INT NULL DEFAULT (0),
    SupplierId NVARCHAR(100) NULL,
    CreatedAt DATETIME NULL DEFAULT (GETDATE()),
    ErpCode NVARCHAR(100) NULL
);
GO

-- Recipes
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'Recipes')
CREATE TABLE Recipes (
    Id INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    TenantId NVARCHAR(50) NOT NULL,
    Name NVARCHAR(MAX) NOT NULL,
    CreatedBy NVARCHAR(100) NULL,
    CreatedAt DATETIME NULL DEFAULT (GETDATE())
);
GO

-- RecipeItems
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'RecipeItems')
CREATE TABLE RecipeItems (
    Id INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    RecipeId INT NOT NULL,
    MaterialId INT NULL,
    Amount FLOAT NOT NULL,
    Unit NVARCHAR(50) NULL
);
GO

-- TemperatureLogs
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'TemperatureLogs')
CREATE TABLE TemperatureLogs (
    Id INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    TenantId NVARCHAR(50) NOT NULL,
    LogDate DATETIME NOT NULL,
    SeraIciSabah FLOAT NULL,
    SeraIciOgle FLOAT NULL,
    SeraIciAksam FLOAT NULL,
    SeraDisiSabah FLOAT NULL,
    SeraDisiOgle FLOAT NULL,
    SeraDisiAksam FLOAT NULL,
    MazotLt FLOAT NULL,
    Note NVARCHAR(MAX) NULL,
    CreatedAt DATETIME NULL DEFAULT (GETDATE())
);
GO

-- ActivityLogs
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'ActivityLogs')
CREATE TABLE ActivityLogs (
    Id INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    TenantId NVARCHAR(50) NOT NULL,
    Action NVARCHAR(100) NULL,
    Title NVARCHAR(MAX) NULL,
    Icon NVARCHAR(50) NULL,
    Color NVARCHAR(100) NULL,
    LogDate DATETIME NULL DEFAULT (GETDATE()),
    Cost FLOAT NULL DEFAULT (0)
);
GO

-- Expenses
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'Expenses')
CREATE TABLE Expenses (
    Id INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    TenantId NVARCHAR(50) NOT NULL,
    BatchId INT NULL,
    Title NVARCHAR(MAX) NULL,
    Amount FLOAT NOT NULL,
    ExpenseType NVARCHAR(50) NULL,
    LogDate DATETIME NULL DEFAULT (GETDATE()),
    ReferenceId NVARCHAR(100) NULL
);
GO

-- FertilizerLogs
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'FertilizerLogs')
CREATE TABLE FertilizerLogs (
    Id INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    TenantId NVARCHAR(50) NOT NULL,
    LogDate DATETIME NOT NULL,
    Fungusit BIT NULL DEFAULT (0),
    AminoAsit BIT NULL DEFAULT (0),
    StartFert BIT NULL DEFAULT (0),
    Note NVARCHAR(MAX) NULL,
    CreatedAt DATETIME NULL DEFAULT (GETDATE())
);
GO

-- Suppliers (referenced by Plants/Purchases)
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'Suppliers')
CREATE TABLE Suppliers (
    Id INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    TenantId NVARCHAR(50) NOT NULL,
    Name NVARCHAR(MAX) NULL,
    Phone NVARCHAR(50) NULL,
    Email NVARCHAR(100) NULL,
    City NVARCHAR(100) NULL,
    CreatedAt DATETIME NULL DEFAULT (GETDATE())
);
GO

-- Orders
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'Orders')
CREATE TABLE Orders (
    Id INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    TenantId NVARCHAR(50) NOT NULL,
    CustomerId INT NULL,
    OrderDate DATETIME NULL DEFAULT (GETDATE()),
    Status NVARCHAR(50) NULL,
    TotalAmount FLOAT NULL DEFAULT (0),
    CompletedAt DATETIME NULL,
    CreatedAt DATETIME NULL DEFAULT (GETDATE())
);
GO

-- OrderItems
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'OrderItems')
CREATE TABLE OrderItems (
    Id INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    OrderId INT NOT NULL,
    PlantId INT NULL,
    Quantity FLOAT NULL DEFAULT (0),
    UnitPrice FLOAT NULL DEFAULT (0)
);
GO

-- Sales
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'Sales')
CREATE TABLE Sales (
    Id INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    TenantId NVARCHAR(50) NOT NULL,
    CustomerId INT NULL,
    InvoiceNo NVARCHAR(50) NULL,
    TotalAmount FLOAT NULL DEFAULT (0),
    IsSynced BIT NULL DEFAULT (0),
    LogDate DATETIME NULL DEFAULT (GETDATE())
);
GO

-- Purchases
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'Purchases')
CREATE TABLE Purchases (
    Id INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    TenantId NVARCHAR(50) NOT NULL,
    SupplierId NVARCHAR(100) NULL,
    SupplierName NVARCHAR(MAX) NULL,
    OrderDate DATETIME NULL DEFAULT (GETDATE()),
    Status NVARCHAR(50) NULL,
    ReceivedDate DATETIME NULL,
    CreatedAt DATETIME NULL DEFAULT (GETDATE()),
    Category NVARCHAR(100) NULL
);
GO

-- PurchaseItems
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'PurchaseItems')
CREATE TABLE PurchaseItems (
    Id INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    PurchaseId INT NOT NULL,
    MaterialId NVARCHAR(100) NULL,
    Amount FLOAT NULL DEFAULT (0),
    UnitPrice FLOAT NULL DEFAULT (0)
);
GO

-- ProductionBatches
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'ProductionBatches')
CREATE TABLE ProductionBatches (
    Id INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    TenantId NVARCHAR(50) NOT NULL,
    LotId NVARCHAR(100) NOT NULL,
    PlantName NVARCHAR(MAX) NULL,
    RecipeId INT NULL,
    Quantity FLOAT NULL DEFAULT (0),
    ViyolCount INT NULL DEFAULT (0),
    StartDate DATETIME NULL DEFAULT (GETDATE()),
    EndDate DATETIME NULL,
    Stage NVARCHAR(50) NULL,
    Location NVARCHAR(100) NULL,
    Status NVARCHAR(50) NULL DEFAULT ('AKTIF'),
    AccumulatedCost FLOAT NULL DEFAULT (0),
    CreatedAt DATETIME NULL DEFAULT (GETDATE())
);
GO

-- ProductionHistory
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'ProductionHistory')
CREATE TABLE ProductionHistory (
    Id INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    BatchId INT NOT NULL,
    LogDate DATETIME NULL DEFAULT (GETDATE()),
    Action NVARCHAR(MAX) NULL,
    Note NVARCHAR(MAX) NULL
);
GO

-- ProductionCostHistory
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'ProductionCostHistory')
CREATE TABLE ProductionCostHistory (
    Id INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    BatchId INT NOT NULL,
    Amount FLOAT NOT NULL,
    CostPerUnit FLOAT NULL,
    Action NVARCHAR(MAX) NULL,
    CostType NVARCHAR(50) NULL,
    LogDate DATETIME NULL DEFAULT (GETDATE())
);
GO

-- SupportTickets
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'SupportTickets')
CREATE TABLE SupportTickets (
    Id INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    TenantId NVARCHAR(50) NOT NULL,
    Subject NVARCHAR(MAX) NULL,
    Description NVARCHAR(MAX) NULL,
    Status NVARCHAR(50) NULL DEFAULT ('NEW'),
    CreatedAt DATETIME NULL DEFAULT (GETDATE())
);
GO

-- SupportHistory
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'SupportHistory')
CREATE TABLE SupportHistory (
    Id INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    TicketId INT NOT NULL,
    Action NVARCHAR(MAX) NULL,
    LogDate DATETIME NULL DEFAULT (GETDATE())
);
GO

PRINT '==========================================';
PRINT 'Tüm ek tablolar başarıyla oluşturuldu!';
PRINT '==========================================';
GO
